name: ${project.artifactId}Plugin
main: th.in.mihome.economyCraft.ECPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
description: ${project.description}
load: POSTWORLD
database: true
softdepend: [Vault]
commands:
    debug1:
    market_bid:
        description: Creates a bidding for an item in the nearest market.
        aliases: [newbid, bid]
        usage: "Usage: /<command> <item_id>[,<item_damage>] <quantity> <bid_price>"
    market_buy:
        description: Creates a bidding for an item in the nearest market with the market price.
        aliases: [buy]
        usage: "Usage: /<command> <item_id>[,<item_damage>] <quantity> <bid_price>"
    market_offer:
        description: Creates an offer for the currently held item in the nearest market. If the amount is not set, defaults to all selected.
        aliases: [newoffer, offer, ask, sell]
        usage: "Usage: /<command> [offer_price] [offer_amount]"
    remove_quote:
        description: Remove a quote previously listed at the nearest market.
        aliases: [debid, removebid, deoffer, removeoffer, delquote, dq]
        usage: "Usage: /<command> [bid_id]"
    list_market_quotes:
        description: Lists all your quotes at the nearest market.
        aliases: [lsquote]
        usage: "Usage: /<command> [side]"
    deposit:
        description: Deposit money at the nearest bank.
        usage: "Usage: /<command> [amount]"
    withdraw:
        description: Withdraw money from the nearest bank.
        usage: "Usage: /<command> [amount]"