name: ${project.artifactId}Plugin
main: th.in.mihome.economyCraft.ECPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
description: ${project.description}
load: POSTWORLD
database: true
softdepend:
commands:
    market_bid:
        description: Creates a bidding for an item in the nearest market.
        aliases: [newbid, bid, buy]
        usage: "Usage: /<command> [item_id] [quantity] [bid_price] [item_data]"
    market_offer:
        description: Creates an offer for the currently held item in the nearest market.
        aliases: [newoffer, offer, ask, sell]
        usage: "Usage: /<command> [offer_price]"
    remove_market_bid:
        description: Withdraws a bid sent in the nearest market.
        aliases: [debid, removebid]
        usage: "Usage: /<command> [bid_id]"
    remove_market_offer:
        description: Withdraws an offer sent in the nearest market.
        aliases: [deoffer, removeoffer]
        usage: "Usage: /<command> [offer_id]"
    list_market_quotes:
        description: Lists all your quotes at the nearest market.
        aliases: [lsquote]
        usage: "Usage: /<command> [side]"
    deposit:
        description: Deposit money at the nearest bank.
        usage: "Usage: /<command> [amount]"
    withdraw:
        description: Withdraw money from the nearest bank.
        usage: "Usage: /<command> [amount]"